//! Audit log — SQLite WAL + HMAC-chain (REQ-KVD-002 Bloque 6, ADR-KVD-007).
//!
//! Public API: [`AuditEvent`], [`AuditLog`], [`AuditWriter`].

pub mod bootstrap;
pub mod export;
pub mod hmac;
pub mod migrations;
pub mod reader;
pub mod schema;
pub mod writer;

use serde::{Deserialize, Serialize};

/// Canonical primitive string for system-level (non-MCP) audit rows such as
/// `vault_created` (REQ-KVD-002 / ISSUE-003) and `home_rebound`
/// (REQ-KVD-008 / ISSUE-019). Distinct from the 7 capability primitives
/// (`kvendra.git`, `kvendra.github`, ...) so dashboards can filter system
/// events without enumerating each action.
pub const PRIMITIVE_SYSTEM: &str = "kvendra.system";

/// Status field of an audit row.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Status {
    Started,
    Ok,
    Error,
}

impl Status {
    pub fn as_str(&self) -> &'static str {
        match self {
            Status::Started => "started",
            Status::Ok => "ok",
            Status::Error => "error",
        }
    }
}

/// Severity level — info | warn | error.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Severity {
    Info,
    Warn,
    Error,
}

impl Severity {
    pub fn as_str(&self) -> &'static str {
        match self {
            Severity::Info => "info",
            Severity::Warn => "warn",
            Severity::Error => "error",
        }
    }
}

/// Logical audit event payload (pre-HMAC).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuditEvent {
    pub ts_unix_ms: i64,
    pub profile_id: String,
    pub primitive: String,
    pub action: String,
    pub args_hash_hex: String,
    pub status: Status,
    pub severity: Severity,
    /// Optional comma-separated flags (e.g. "unsafe_escape_hatch").
    pub flags: String,
    /// ULID returned by the remote broker (`tokens:issue` audit_id field).
    /// `None` for rows generated by `LocalVaultResolver` and for every row
    /// that pre-dates the v2 migration (REQ-KVD-CLI-010).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub remote_audit_id: Option<String>,
}

pub use writer::AuditWriter;
